name: Main CI

on:
  push:
  pull_request:
    branches:
      - main

env:
  MAVEN_ARGS: "--batch-mode --no-transfer-progress --show-version"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12  # v4.7.0
        with:
          distribution: temurin
          java-version: 17
      - name: Run Spotless
        run: mvn spotless:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12  # v4.7.0
        with:
          distribution: temurin
          java-version: 17
      - name: Build, test and verify with Maven
        run: mvn verify
      - name: Archive build artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: build
          path: target/
